// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvYkAX7wxV-vZhKllMnBnjaetAAbzyg0I',
    appId: '1:808205003599:web:59f68bb5218e872f20f33a',
    messagingSenderId: '808205003599',
    projectId: 'shoppingapp-1c6a9',
    authDomain: 'shoppingapp-1c6a9.firebaseapp.com',
    storageBucket: 'shoppingapp-1c6a9.appspot.com',
    measurementId: 'G-FRN4HGN8QZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA6GIIF5XF4VUZCMm8PtrTnvz52-pQTjU',
    appId: '1:808205003599:android:3eea3f44d90f254820f33a',
    messagingSenderId: '808205003599',
    projectId: 'shoppingapp-1c6a9',
    storageBucket: 'shoppingapp-1c6a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCONSWvkLRQB26sflVsrdrR1pHGMaP1Ig4',
    appId: '1:808205003599:ios:76485d0fcce471e620f33a',
    messagingSenderId: '808205003599',
    projectId: 'shoppingapp-1c6a9',
    storageBucket: 'shoppingapp-1c6a9.appspot.com',
    iosClientId: '808205003599-vhiqihknaqjfv4m24ptv1bir3mtiibnd.apps.googleusercontent.com',
    iosBundleId: 'com.example.eKart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCONSWvkLRQB26sflVsrdrR1pHGMaP1Ig4',
    appId: '1:808205003599:ios:174f664b8b2b9cdf20f33a',
    messagingSenderId: '808205003599',
    projectId: 'shoppingapp-1c6a9',
    storageBucket: 'shoppingapp-1c6a9.appspot.com',
    iosClientId: '808205003599-to8j367nhqb716lc64e67nfb85vhhrn9.apps.googleusercontent.com',
    iosBundleId: 'com.example.eKart.RunnerTests',
  );
}
